#!/usr/bin/env python3
"""Populate expected_hash + accepted_hashes in each suite's manifest.toml
from the tier-promoted references.json.

Rule per (test, bios_mode):
    expected_hash = the gold-tier consensus hash if one exists
    accepted_hashes = all hashes from all runners under that mode

Manifests previously stored a single empty `expected_hash = ""` per test;
they now store a `[tests.expected]` table mapping each bios_mode to its
canonical hash plus an `accepted` list. Cable Club's accuracy_sweep.rs
already understands schema-v2 references.json, so this is purely a
manifest-side aid for human readability and external tools.

Usage:
    python scripts/populate_expected.py
    python scripts/populate_expected.py --suite jsmolka
    python scripts/populate_expected.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SUITES_DIR = REPO_ROOT / "suites"

MIN_VOTES_FOR_CONSENSUS = 2


def _bios_mode_of(entry: dict) -> str:
    return entry.get("bios_mode") or entry.get("provenance", {}).get("bios_mode") or "hle"


def derive_expected(refs_path: Path) -> dict[str, dict]:
    """Returns {test_id: {bios_mode: {"expected": hash|None, "accepted": [hash, ...]}}}."""
    with open(refs_path) as f:
        refs = json.load(f)
    out: dict[str, dict] = {}
    for test_id, entries in refs.get("references", {}).items():
        by_mode: dict[str, list[dict]] = defaultdict(list)
        for e in entries:
            by_mode[_bios_mode_of(e)].append(e)
        per_mode: dict[str, dict] = {}
        for mode, mode_entries in by_mode.items():
            counter = Counter(e["hash"] for e in mode_entries if e.get("hash"))
            if not counter:
                continue
            top, top_count = counter.most_common(1)[0]
            expected = top if top_count >= MIN_VOTES_FOR_CONSENSUS else None
            per_mode[mode] = {"expected": expected, "accepted": list(counter.keys())}
        if per_mode:
            out[test_id] = per_mode
    return out


def _format_toml_block(test_id: str, modes: dict[str, dict]) -> str:
    """Render a [tests.expected.<test_id>] block. We do this with hand-rolled
    TOML so we don't have to round-trip the entire manifest through tomli_w
    (which would lose comments)."""
    lines = [f'[tests.expected."{test_id}"]']
    for mode in sorted(modes):
        entry = modes[mode]
        if entry["expected"]:
            lines.append(f'{mode}_expected = "{entry["expected"]}"')
        accepted = entry["accepted"]
        accepted_csv = ", ".join(f'"{h}"' for h in accepted)
        lines.append(f'{mode}_accepted = [{accepted_csv}]')
    return "\n".join(lines) + "\n"


def write_expected_block(suite_dir: Path, expected: dict, dry_run: bool = False) -> str:
    """Write a separate `expected.toml` next to the manifest. We DON'T touch
    manifest.toml itself — appending [tests.expected] sub-tables to a TOML
    file with [[tests]] arrays of tables risks parser confusion. Cable Club
    and the Python harness both already read references.json directly; this
    file is for human consumption and external tooling."""
    out_path = suite_dir / "expected.toml"
    blocks = [
        "# Auto-generated by scripts/populate_expected.py.",
        "# Per-test consensus hashes derived from references.json.",
        "# 'expected' is the modal hash where >= 2 runners agree under that BIOS mode.",
        "# 'accepted' is every distinct hash captured under that BIOS mode (any tier).",
        "",
    ]
    for test_id in sorted(expected):
        blocks.append(_format_toml_block(test_id, expected[test_id]))
    body = "\n".join(blocks)
    if not dry_run:
        out_path.write_text(body, encoding="utf-8")
    return body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Populate expected.toml from references.json")
    parser.add_argument("--suite", "-s")
    parser.add_argument("--dry-run", "-n", action="store_true")
    args = parser.parse_args(argv)

    if args.suite:
        suites = [SUITES_DIR / args.suite]
    else:
        suites = sorted(p for p in SUITES_DIR.iterdir() if p.is_dir())

    print(f"Populating expected.toml across {len(suites)} suite(s)")
    print()
    for s in suites:
        refs_path = s / "references.json"
        if not refs_path.exists():
            continue
        expected = derive_expected(refs_path)
        body = write_expected_block(s, expected, dry_run=args.dry_run)
        n_tests = len(expected)
        n_consensus = sum(
            1
            for modes in expected.values()
            if any(m.get("expected") for m in modes.values())
        )
        print(f"  [{s.name:14}] tests={n_tests:3}  with-consensus={n_consensus:3}")
        if args.dry_run:
            print()
            print(body[:600])
            print("...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
